"""Make every figure of docs/redmapper_dr11.rst and its table of numbers.

    python docs/figures/redmapper_dr11/make_all.py [--force] [--only fig_redshifts ...] [--table]

Runs prepare.py (``--force`` redoes its products), then each fig_*.py script in its own process,
then writes values.rst (DR11 numbers next to the literature) from the values.json that the
scripts fill. ``--table`` only rewrites values.rst.
"""

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
SCRIPTS = ["fig_redsequence", "fig_redshifts", "fig_richness", "fig_abundance", "fig_centering", "fig_external",
           "fig_members"]


def fmt(v, spec):
    if v is None:
        return "—"
    if callable(spec):
        return spec(v)
    return format(v, spec)


def pct(v):
    return f"{100 * v:.1f}%"


def pair(i, spec=".2f"):
    return lambda v: format(v[i], spec)


# (quantity, key in values.json, format, literature)
ROWS = [
    ("Area of the run [deg²]", "area_total", ",.0f", "SDSS DR8 10,134 (R16); DES Y1 1,437; LS DR10 grz 19,342 (K24)"),
    ("Median 10σ z-band depth [mag]", "depth_z10", ".2f", ""),
    ("Median z_vlim (0.2 L*, 10σ) at the clusters", "median_zvlim", ".3f", "≈ 0.7 (K24, grz)"),
    ("z_vlim − ZVLIM_02 of K24 at the eRASS1 clusters", "zvlim_minus_k24", "+.3f", "0 if the depth maps agree"),
    ("Clusters λ ≥ 20 with z_λ < z_vlim, per deg² of the run", "nA_lam20", ".2f",
     "SDSS DR8 2.6, DES SV 6.8 (R16); LS DR10 5.8 for λ_norm > 16 (K24)"),
    ("Comoving density, λ ≥ 20, 0.15 < z < 0.55 [h³ Mpc⁻³]", "nV_lam20", ".2e", "≈ 1.2 × 10⁻⁵ at z < 0.35 (R14 Fig. 18)"),
    ("z_λ bias, median Δz/(1+z), λ ≥ 20, z < 0.6", "zl_all_bias", "+.4f", "< 0.005 (R16 DR8); +0.0004 at 0.05–0.4 (K24)"),
    ("z_λ scatter, NMAD of Δz/(1+z)", "zl_all_nmad", ".4f", "0.006–0.02 (R14); ≈ 0.01 (R16)"),
    ("Mean σ_zλ/(1+z)", "zl_all_err", ".4f", ""),
    ("4σ outliers (central spec-z)", "zl_all_out4", pct, "≈ 1% (R14); 1.1% (R16 DR8)"),
    ("4σ outliers, ≥ 2 spectroscopic members", "zl_clean_out4", pct, "≲ 0.2% (R14)"),
    ("Σ P(z) against N(z_spec), λ ≥ 20: χ² / bins", "pz_chi2", lambda v: f"{v[0]:.0f} / {v[1]}", ""),
    ("Empirical / formal z_λ error (K24 sample)", "zl_k24_emp_over_formal", ".2f", "≈ 1, up to 2 at z > 0.8 (K24)"),
    ("⟨P_cen⟩, λ ≥ 20", "pcen_mean_lam20", ".2f", "0.82 predicted (R16)"),
    ("Well-centred fraction ρ0, eRASS1 X-ray", "centring_erass1", pair(0), "0.78 ± 0.11 (R16, X-ray and SZ)"),
    ("Well-centred fraction ρ0, ACT DR6 SZ", "centring_act_dr6", pair(0), ""),
    ("Well-centred fraction ρ0, SPT-SZ", "centring_spt_2500d", pair(0), ""),
    ("Miscentring width σ1 [R_λ], eRASS1", "centring_erass1", pair(2), "0.31 (R16)"),
    ("Same central as DES Y1 redMaPPer", "centring_same_des_y1", lambda v: pct(v[0]), ""),
    ("Same central as SDSS DR8 redMaPPer", "centring_same_sdss_dr8", lambda v: pct(v[0]), ""),
    ("λ / λ(DES Y1), median, λ_DES ≥ 20", "lam_ratio_des_y1", ".2f", "0.79 for LS DR10 λ_norm (K24)"),
    ("λ / λ(SDSS DR8), median, λ_SDSS ≥ 20", "lam_ratio_sdss_dr8", ".2f", "1/(1.04 + 0.17 e^{5.4(z−0.36)}) (IC20)"),
    ("λ / λ_norm (K24, eRASS1 positions)", "lam_ratio_erass1", ".2f", "1.039 expected (griz vs grz, K24)"),
    ("λ–σ_v slope (orthogonal fit, ≥ 15 members)", "lam_sigma_fit", pair(0), "2.40 (K24)"),
    ("Recovered ACT DR6 clusters", "recovery_act_dr6", lambda v: pct(v[0]), "> 95% (K24, scan mode)"),
    ("Recovered SPT-SZ 2500d clusters", "recovery_spt_2500d", lambda v: pct(v[0]), "> 95% (K24, scan mode)"),
    ("Recovered Planck PSZ2 clusters", "recovery_psz2", lambda v: pct(v[0]), "> 95% (K24, scan mode)"),
    ("Recovered eRASS1 clusters (PCONT < 0.5)", "recovery_erass1", lambda v: pct(v[0]), ""),
    ("Recovered MCXC clusters", "recovery_mcxc", lambda v: pct(v[0]), ""),
    ("λ ≥ 20 clusters with a Wen & Han (2024) counterpart", "wh_frac_lam20", pct, ""),
]


def write_table(values: dict, path: Path):
    lines = [".. Generated by docs/figures/redmapper_dr11/make_all.py: do not edit.", "",
             ".. list-table::", "   :header-rows: 1", "   :widths: 44 14 42", "",
             "   * - Quantity", "     - DR11 (rema)", "     - Literature"]
    for label, key, spec, lit in ROWS:
        v = values.get(key)
        try:
            text = fmt(v, spec)
        except (TypeError, ValueError, IndexError):
            text = "—"
        lines += [f"   * - {label}", f"     - {text}", f"     - {lit or '—'}"]
    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path.name}")


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--force", action="store_true", help="redo the products of prepare.py")
    p.add_argument("--only", nargs="*", help="run only these fig_* scripts")
    p.add_argument("--table", action="store_true", help="only rewrite values.rst")
    args = p.parse_args(argv)
    env = {**os.environ, "JAX_PLATFORMS": os.environ.get("JAX_PLATFORMS", "cpu"), "PYTHONUNBUFFERED": "1"}
    sys.path.insert(0, str(HERE))
    if not args.table:
        steps = [["prepare.py"] + (["--force"] if args.force else [])] + \
                [[f"{s}.py"] for s in (args.only or SCRIPTS)]
        failed = []
        for step in steps:
            t0 = time.time()
            print(f"--- {step[0]}", flush=True)
            r = subprocess.run([sys.executable, str(HERE / step[0]), *step[1:]], env=env, cwd=HERE)
            print(f"--- {step[0]}: {'ok' if r.returncode == 0 else 'FAILED'} ({time.time() - t0:.0f} s)", flush=True)
            if r.returncode:
                failed.append(step[0])
                if step[0] == "prepare.py":
                    sys.exit(1)
        if failed:
            print("failed:", failed)
    from common import VALUES_FILE

    values = json.loads(VALUES_FILE.read_text()) if VALUES_FILE.exists() else {}
    write_table(values, HERE / "values.rst")


if __name__ == "__main__":
    main()
